helmChartInflationGenerator:
- chartName: kyverno
  chartRepoUrl: https://kyverno.github.io/kyverno/
  chartVersion: v1.3.2
  releaseName: kyverno
  releaseNamespace: operations
  values: https://raw.githubusercontent.com/pdorczuk-kubeshield/kube-system-apps/master/kyverno/kyverno-values.yaml
  extraArgs:
  - --include-crds

resources:
- github.com/pdorczuk-kubeshield/kubeshield-policies//policies

commonLabels:
  team: operations
namespace: operations