helmChartInflationGenerator:
- chartName: argo-cd
  chartRepoUrl: https://argoproj.github.io/argo-helm
  chartVersion: v2.11.6
  releaseName: argocd
  releaseNamespace: operations
  values: argocd-values.yaml
  extraArgs:
  - --include-crds

namespace: operations

resources:
- sealedsecret.yaml
- ingress-https.yaml
- ingress-grpc.yaml

patchesStrategicMerge:
- patch_sealedsecret_manage_argo_secret.yaml