helmChartInflationGenerator:
- chartName: sealed-secrets
  chartRepoUrl: https://bitnami-labs.github.io/sealed-secrets
  chartVersion: v1.14.1-r1
  releaseName: sealedsecrets
  releaseNamespace: operations
  values: sealedsecrets-values.yaml
  extraArgs:
  - --include-crds

resources:
- namespace.yaml

namespace: operations